services:
    # ! IMPORTANT Modify these depending on where you placed your gcloud credentials keyfile
    # example:
    # - /home/<your-username>/.keys/project_creds.json:/usr/local/airflow/gcloud/project_creds.json:rw
    scheduler:
        volumes:
        # replace this one
        - /home/charles/.keys/project_creds.json:/usr/local/airflow/gcloud/project_creds.json:rw
    webserver:
        volumes:
        # this one too...
        - /home/charles/.keys/project_creds.json:/usr/local/airflow/gcloud/project_creds.json:rw
    triggerer:
        volumes:
        # ...and lastly this one
        - /home/charles/.keys/project_creds.json:/usr/local/airflow/gcloud/project_creds.json:rw